FROM nginx:1.18-alpine

COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./api.eventhub.ch.crt /etc/nginx/api.eventhub.ch.crt
COPY ./api.eventhub.ch.key /etc/nginx/api.eventhub.ch.key
COPY ./eventhub.ch.crt /etc/nginx/eventhub.ch.crt
COPY ./eventhub.ch.key /etc/nginx/eventhub.ch.key
